### ISSUE TITLE
能否提供 一个 docker 部署的方法

### ISSUE THREAD

**Issue by lucktoo** [Slowlyo/owl-admin#10]
部署各种问题, mac

**Comment by lucktoo** [comment]
<img width="532" alt="image" src="https://github.com/Slowlyo/owl-admin/assets/23254843/86f2c7fe-c1eb-45b4-8a9a-684dfb2c7979">
不知道怎么回事? 环境缺对象 还是 ?
<img width="1566" alt="image" src="https://github.com/Slowlyo/owl-admin/assets/23254843/52168ddf-f327-40ab-a5e6-a921222810b4">

**Comment by Slowlyo** [comment]
访问127.0.0.1:8000/admin试试?

**Comment by lucktoo** [comment]
解决了 是这样.还有一个问题 就是这么切换成中文呢
