### ISSUE TITLE
树形列表分页显示异常

### ISSUE THREAD

**Issue by leoxml** [slowlyo/owl-admin#102]
### 描述问题：

树形结构的列表数据，当超过20条时，按理说应该自动分页，当前情况是：

列表左下角会有总条数和总页数，但列表右下角没有翻页控件

### 截图或视频：

![531543528c5428b299a7f0d1d26a4042](https://github.com/slowlyo/owl-admin/assets/6308377/37da6867-0e1c-4633-8ba0-fed1c4ac7376)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

v3.5.8

2. PHP & Laravel 版本是什么？

php8.3 & laravel: 11.*.*

3. 运行环境

`Linux`

4. 操作步骤

**Comment by slowlyo** [comment]
目前没有太好的解决方案, 可以设置prePage属性为999将数据展示完整, 或者使用懒加载
