### ISSUE TITLE
ImageControl组件定义maxSize以后第一次上传超限制不提示并报错

### ISSUE THREAD

**Issue by maliang** [slowlyo/owl-admin#105]
### 描述问题：

ImageControl组件定义maxSize以后第一次上传超限制不提示并报错

### 截图或视频：

![image](https://github.com/slowlyo/owl-admin/assets/367390/5eb067c3-84ef-4f5f-be37-ccb78d2ef769)
![image](https://github.com/slowlyo/owl-admin/assets/367390/98fd6bdd-6e61-4e2e-8392-16e530872e3f)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

3.6.2

2. PHP & Laravel 版本是什么？

php8.2 & laravel: 11.6.*

3. 运行环境

Win + Docker

4. 操作步骤

`
amis()->ImageControl('avatar', 'logo')->maxSize(102400)
`

**Comment by slowlyo** [comment]
v3.6.4 已修复
