### ISSUE TITLE
非弹窗下，详情无法渲染关联字段信息

### ISSUE THREAD

**Issue by kanganxi** [slowlyo/owl-admin#108]
### 描述问题：

非弹窗下，查看详情 无法渲染关联字段信息，比如:node.name
`  amis()->TextControl('node.name', '所属节点')->static(),`

1. owl-admin 版本是什么？

 owl-admin 3.6

2. PHP & Laravel 版本是什么？

php8.2& laravel: 10.*.*

3. 运行环境

 `Mac + Herd` 

4. 操作步骤

列表--查看详情按钮（非弹窗模式下）

**Comment by slowlyo** [comment]
因为弹窗模式下, 详情的数据可以从列表获取, 然后列表的数据是可以动态加载关联关系的

如果是页面模式的详情的话, 需要手动添加 with 查询
