### ISSUE TITLE
菜单栏选中问题

### ISSUE THREAD

**Issue by YouLiLiao** [slowlyo/owl-admin#113]
刷新后，无法再选中
![image](https://github.com/slowlyo/owl-admin/assets/11286354/c88eb7a5-ba18-4953-83ce-7153b5f1210f)
![image](https://github.com/slowlyo/owl-admin/assets/11286354/a2f303be-b515-424a-bbb6-96164564f285)

**Comment by slowlyo** [comment]
包含在菜单数据中的路由, 才会在刷新后重新选中

**Comment by YouLiLiao** [comment]
> 包含在菜单数据中的路由, 才会在刷新后重新选中

![image](https://github.com/slowlyo/owl-admin/assets/11286354/647a0824-7946-465e-b0b5-f3f9d4f8ffa0)
![image](https://github.com/slowlyo/owl-admin/assets/11286354/d54287aa-167a-49bd-a8e3-e337f0f24292)
这样也不可以吗？

**Comment by YouLiLiao** [comment]
/users/1这个路径就可以选中，但是后面再加就不会选中了

**Comment by slowlyo** [comment]
框架无法识别这样的路由
