### ISSUE TITLE
bug: 代码生成器中编辑已经存在的记录，出现错误

### ISSUE THREAD

**Issue by emonduora** [slowlyo/owl-admin#114]
<img width="382" alt="image" src="https://github.com/slowlyo/owl-admin/assets/156265314/51b439ce-decc-43ca-b4e0-2c6e5c2ff64d">

版本3.7，对已经存在的记录进行编辑后保存时出现如上错误，也无法进行预览

**Comment by slowlyo** [comment]
更新  v3.7.1
