### ISSUE TITLE
edit页面存在缓存 没自动刷新

### ISSUE THREAD

**Issue by CarefreeUI** [slowlyo/owl-admin#118]
### 描述问题：

edit页面存在缓存 没自动刷新

### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

3.7

2. PHP & Laravel 版本是什么？

php8.1 & laravel: 10.*.*

3. 操作步骤

不使用弹窗编辑 使用单独页面edit编辑操作 保存后再切换回来数据没变 刷新后重新加载才有变化

**Comment by slowlyo** [comment]
开了页面缓存是吗

**Comment by CarefreeUI** [comment]
> 开了页面缓存是吗

之前开了从3.2版本一路到3.7版本 37时候开了下全局页面缓存 然后又关了 目前是列表等页面都正常 只有单独的edit页面似乎是留有缓存

**Comment by slowlyo** [comment]
清缓存/换浏览器看看呢

**Comment by CarefreeUI** [comment]
不行呢 不管是服务器部署了还是其他人使用 都是这个样子
保存后会跳转到列表 编辑界面会关闭 但是不刷新再次打开编辑 依然是前一次的缓存一样

**Comment by slowlyo** [comment]
测试了一下, 并没有这个问题, 即使开启了页面缓存, 编辑页面数据也是会正常更新的

检查一下自己的代码逻辑

**Comment by CarefreeUI** [comment]
可能是 我回退到339就好了
