### ISSUE TITLE
我使用了amis json   转换成了php. 然后不知道怎么做了?不是低代码吗?

### ISSUE THREAD

**Issue by lucktoo** [Slowlyo/owl-admin#12]
amisMake()->Page()->title('Hello world')->body([amisMake()->Grid()->columns([['body' => [],'id' => 'u:2dc45a289b0c',],['body' => [],'id' => 'u:1eac9b6bc5ff',],])->id('u:e8393964b69f'),amisMake()->Form()->title('表单')->body([amisMake()->TextControl()->label('文本框')->name('text')->id('u:43626c35f4e3'),])->id('u:ce4245bc3f1e')->actions([amisMake()->TagControl()->label('标签')->name('tag')->options(['0' => '红色','1' => '绿色','2' => '蓝色',])->id('u:39bcc8d9ebb4'),]),amisMake()->InputExcel()->label('Excel')->name('excel')->id('u:273029d76a40'),])->id('u:59f968412d70')

转换成了 php,  在那个地方使用这个代码生成界面呢?
初学者,不好意思,文档看了半天没看明白
辛苦大佬帮帮忙

**Comment by 1821725017** [comment]
754544686

加群提问
