### ISSUE TITLE
问个简单问题，数据库配置，配在哪里呢，没找着.env文件。只有admin_view那有一个

### ISSUE THREAD

**Issue by jasonLaw1015** [slowlyo/owl-admin#136]
数据库配置，配在哪里呢，没找着.env文件。只有admin_view那有一个

还是在这个配置文件里加就好了
![image](https://github.com/slowlyo/owl-admin/assets/28339015/55fa0b58-e4fb-4ed2-b7a9-9de31c7ff4cf)

**Comment by slowlyo** [comment]
注意看 readme

owl-admin 是 laravel 的扩展包, 并不是 clone 就能使用的哈

**Comment by jasonLaw1015** [comment]
噢噢。
明白了
