### ISSUE TITLE
[Feature Request] Service 层集中转换

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [slowlyo/owl-admin#143]
### 是否关联于某个问题吗：

amis 的 ImageControl 需要 url, 但是项目的关联查询出来的是个对象, url 是其中一个属性
在 Model 写 Attribute 的方式我认为不太好, 因为只有管理后台需要用到这种格式

### 预期的解决方案：

是否可以在 Service 层写一个集中的转换方法, 比如 cast 方法用于集中转换处理

### 其他可接受方案：

我目前使用的方案是手动修改 `getDetail` 和 `getEditData` 方法的返回结果, 并返回修改后的数据

### 任何附加信息：

**Comment by slowlyo** [comment]
Attribute 只是解决方案之一, 根据自己的业务自行调整处理逻辑就行
