### ISSUE TITLE
Admin 删除自身权限

### ISSUE THREAD

**Issue by ck97756** [slowlyo/owl-admin#148]
### 描述问题：

试用 Demo 网站时
把 Admin 的超级用户权限删除
造成无法使用任何功能

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

Version: v3.9.7 

3. 运行环境

http://demo.owladmin.com

**Comment by slowlyo** [comment]
- demo 站点已恢复
- 会在后续版本中优化这个问题
