### ISSUE TITLE
渲染组件拆分为独立的php包

### ISSUE THREAD

**Issue by ywisax** [slowlyo/owl-admin#149]
### 预期的解决方案：
https://github.com/slowlyo/owl-admin/tree/master/src/Renderers 这里面的代码组织得很好。
是否可能拆分这部分为独立的php包？这样子其他框架使用amis就能复用这部分。

### 其他可接受方案：
复制代码。。。

**Comment by slowlyo** [comment]
有这么做过 但是没有精力维护 搁置了
