### ISSUE TITLE
设置了Token有效期后登录判断有问题

### ISSUE THREAD

**Issue by halo123450** [slowlyo/owl-admin#153]
### 描述问题：
最新版本新增了判断Token使用有效期的逻辑,但是登录成功后last_used_at值为空,导致登录后Token无效

### 截图或视频：

![image](https://github.com/user-attachments/assets/d32a9010-3fdc-4e76-83d9-598b7714c650)
![image](https://github.com/user-attachments/assets/683cfd44-fff1-41d6-a2ed-b11933147c22)
![image](https://github.com/user-attachments/assets/a859b936-c170-4042-b12a-2b6db0886e74)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？
   v4.0.1

3. PHP & Laravel 版本是什么？

php8.2 & laravel: 11.25.0

4. 运行环境

`Linux + Centos7.9`
 
5. 操作步骤
.env 设置
# token 有效期 (分钟), 为空则不会过期
ADMIN_TOKEN_EXPIRATION=1440
请求登录接口
/admin-api/login
{
    "username": "xxxxx",
    "password": "xxxxx",
    "remember": true,
    "captcha": "4GNZ",
    "sys_captcha": "captcha:66f82631cc0ee"
}

获取Token后Token为无效值因为执行的SQL为
select * from `personal_access_tokens` where `last_used_at` >= '2024-09-27 23:54:35' and `personal_access_tokens`.`id` = 76 limit 1
而`personal_access_tokens`表中的`last_used_at` 字段值 IS NULL

**Comment by slowlyo** [comment]
于 [v4.0.2](https://github.com/slowlyo/owl-admin/releases/tag/v4.0.2) 已修复
