### ISSUE TITLE
左数右表的问题

### ISSUE THREAD

**Issue by huangzz1024** [slowlyo/owl-admin#154]
### 描述问题：

在官网给出的demo中，使用左数右表。
Tree模式时，点击左数的除了文字外的地方没有效果，希望点击整行都是一样效果。
Nav模式时，只有点击箭头才展开，希望点击整行都右展开和收缩的效果

### 截图或视频：

![image](https://github.com/user-attachments/assets/f4c25b3e-9468-4e2f-88b6-695bf2417ef2)
![Uploading image.png…]()

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

官网demo

2. PHP & Laravel 版本是什么？

php8.3 & laravel: 10.*.*

3. 运行环境

eg: `Win + Docker` `Mac + Sail` `Linux + BT`

4. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by slowlyo** [comment]
这个是amis组件的问题, 可以去amis反馈
