### ISSUE TITLE
搜索如何设置全等

### ISSUE THREAD

**Issue by meilikeai** [slowlyo/owl-admin#158]
### 描述问题：

在后台使用筛选时，控制选项为select框时，用id做匹配时，查询条件时like。这里是我使用的问题吗

### 截图或视频：

![image](https://github.com/user-attachments/assets/611762ba-8fb6-41d2-86a4-3789546f9000)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

4.0

2. PHP & Laravel 版本是什么？

php8.2 & laravel: 11

3. 运行环境

wsl乌班图

4. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by slowlyo** [comment]
重写 service 中的 searchable 方法

**Comment by meilikeai** [comment]
![image](https://github.com/user-attachments/assets/8aa596b2-7a25-4211-9fb2-4e1e4e52038d)

**Comment by meilikeai** [comment]
> 重写 service 中的 searchable 方法

行，主要是不想去改底层的东西，不然下版本更新不了，只能这样解决的话，那我改改

**Comment by slowlyo** [comment]
> > 重写 service 中的 searchable 方法
> 
> 行，主要是不想去改底层的东西，不然下版本更新不了，只能这样解决的话，那我改改

 重写...不是让你改源码...    继承 重写

**Comment by meilikeai** [comment]
发现不是简单的调整这一项，如果存在in和范围啥的，都不行。。有没有调整这一块的计划？

**Comment by slowlyo** [comment]
> 发现不是简单的调整这一项，如果存在in和范围啥的，都不行。。有没有调整这一块的计划？

所以让你在对应的service里面按照你自己的业务逻辑重写 searchable方法啊, 框架默认的逻辑只提供简单的模糊查询

**Comment by meilikeai** [comment]
我去研究下能不能把dcat的那块搞过来，这样太麻烦了，能直接指定查询方式最好。感谢~
