### ISSUE TITLE
有没有使用cos，oss这些对象存储的对接方案。

### ISSUE THREAD

**Issue by qq781548819** [slowlyo/owl-admin#159]
### 是否关联于某个问题吗：
有没有使用cos，oss这些对象存储的对接方案。

使用的微信云托管，服务端上传文件限制了1m，只能在web h5端传到cos。

https://developers.weixin.qq.com/community/develop/doc/00002cd09e8c88464761db1f06b400
![image](https://github.com/user-attachments/assets/b9c50412-3635-4b8a-b616-c3de11d97083)
![image](https://github.com/user-attachments/assets/90505e11-ae3a-48df-80d0-fc202a375927)

**Comment by qq781548819** [comment]
文档：https://developers.weixin.qq.com/miniprogram/dev/wxcloudrun/src/development/storage/service/upload.html

**Comment by slowlyo** [comment]
参考这个: https://github.com/slowlyo/owl-admin/discussions/27

或者把文件传到后端之后由后端上传到微信
