### ISSUE TITLE
导出参数异常

### ISSUE THREAD

**Issue by lifetin** [slowlyo/owl-admin#161]
最新版
搜索后,请求路径是这样的(注意参数: device[name]=测试设备 )
/admin#/dianliu?page=33&day=2024-11-09&start_day=2024-11-08&device[name]=测试设备&perPage=20

我的过滤器是

``
$this->baseFilter()->body([
					amis()->TextControl('device.name', '设备名称')->size('md'),
	])->submitOnChange()
```


再点导出全部 ,请求参数成为下面这样了.  导至后台不能得到device[name]
![image](https://github.com/user-attachments/assets/95b1b0d1-eccb-4c1d-a84a-f3927d4d75a6)

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/fcaf081e-78f6-4036-8b96-b419fab9271b)

**Comment by slowlyo** [comment]
导出的请求是在 amis 中通过 js 处理的, 后面看一下能不能处理, 先改下参数名临时解决一下吧

**Comment by lifetin** [comment]
期待大佬修复
