### ISSUE TITLE
最新版,有个报错,创建新用户界面,进入就这样

### ISSUE THREAD

**Issue by lifetin** [slowlyo/owl-admin#164]
最新版,有个报错,创建新用户界面,进入就这样

![image](https://github.com/user-attachments/assets/79c12e9c-0d3b-48e0-862a-d1abb0b16826)

**Comment by slowlyo** [comment]
这是因为没有查到用户吧, 无法复现

**Comment by lifetin** [comment]
明白,没找到数据引起的.
