### ISSUE TITLE
组件鉴权这块只有permission验证,是否能加个角色验证的?

### ISSUE THREAD

**Issue by lifetin** [slowlyo/owl-admin#165]
组件鉴权这块只有permission验证,是否能加个角色验证的?
比喻是超管,或是传的角色名就显示组件

![image](https://github.com/user-attachments/assets/0f985989-ab98-4d3d-91eb-f140277edd86)

**Comment by slowlyo** [comment]
可以直接 visible() 传入 bool 值来实现

**Comment by lifetin** [comment]
好的, 这样也能解决问题. 如果在框架底层加入效果更好.感谢!!!
