### ISSUE TITLE
4.0.7更新后 生成表单时未处理前缀信息，导致获取不到字段信息

### ISSUE THREAD

**Issue by meilikeai** [slowlyo/owl-admin#169]
### 描述问题：
最新更新有点问题，就是没有处理好表前缀的问题，导致生成的时候获取不到字段信息，表格也是携带前缀的

### 截图或视频：

vendor/slowlyo/owl-admin/src/Support/CodeGenerator/Generator.php
![image](https://github.com/user-attachments/assets/07007169-bf14-40a7-9d71-447ba8c41378)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

4.0.7

2. PHP & Laravel 版本是什么？

php8.2 & laravel: 11

3. 运行环境

eg: `Win + Docker` `Mac + Sail` `Linux + BT`

4. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by slowlyo** [comment]
感谢反馈, 该问题在 [v4.0.8](https://github.com/slowlyo/owl-admin/releases/tag/v4.0.8) 中已修复

建议使用 `Str::replaceStart` 方法替换, 避免出现表明替换异常的问题
