### ISSUE TITLE
请教下ImageControl 显示图片不对的问题

### ISSUE THREAD

**Issue by j4946337** [slowlyo/owl-admin#171]
### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
上传图片以后是存到public/storage/images/image.jpg 下 但是 获取图片地址是 /images/image.jpg
`amis()->ImageControl(logo', 'logo')
                    ->autoUpload(true)
                    ->maxLength(1)
                    ->multiple(false)
                    ->set('url', '/storage/${logo}')->set('src', '/storage/${logo}')->static(),`
这么修改也是不行
### 截图或视频：

![image](https://github.com/user-attachments/assets/4a9bc9e8-e508-43c4-acd5-aa57527e8f72)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

4.0.9

2. PHP & Laravel 版本是什么？

PHP 8.3.11
Lavavel 11.33.2

3. 运行环境

Win + composer run dev

4. 操作步骤

就是上传图片以后无法获取正确的路径 缺少一个 storage 谢谢

**Comment by slowlyo** [comment]
https://github.com/slowlyo/owl-admin/discussions/14

**Comment by slowlyo** [comment]
imageControl 通常不需要做任何处理, 只配置 name 和 label 即可
