### ISSUE TITLE
想实现一个功能，有些情况下是需要使用的

### ISSUE THREAD

**Issue by meilikeai** [slowlyo/owl-admin#174]
### 是否关联于某个问题吗：
![image](https://github.com/user-attachments/assets/1dbf06ef-14cd-4fa1-8909-8ffe962593a8)
删除这里只有一个删除后的操作，但是如果需要获取到源数据是做一些操作时，在事务删除后没有办法获取到源信息，导致一些功能实现不了，当然现在是可以重写方法去实现

### 预期的解决方案：
也可以添加一个钩子方法在删除前去执行某些操作

### 其他可接受方案：
请简单描述其他你可以接受的效果...

### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by slowlyo** [comment]
删除这里代码很少，所以最开始考虑的是有需要就直接重写整个方法，后续可以考虑下再加个钩子🤣

**Comment by meilikeai** [comment]
🤣🤣

**Comment by meilikeai** [comment]
close
