### ISSUE TITLE
each循环时，键名相同，导致数据重复渲染问题

### ISSUE THREAD

**Issue by develop-kevin** [Slowlyo/owl-admin#31]
amisMake()->Each()->name('children')->items([
  amisMake()->Page()->body('${question_stem|truncate: 9999999999 }'),
  amisMake()->Each()->name('children')->items([
  amisMake()->Page()->body('${question_stem|truncate: 9999999999 }'),
  ])
]
使用行政区域地址递归子类，3层以上，名字相同，会出现重复渲染问题，主要是无法找到键值去循环数据

**Comment by Slowlyo** [comment]
这属于是amis的特性了, 他的数据域的逻辑就是这样, 可以到amis下反馈, 或者想想其他曲线救国的方案🤣
