### ISSUE TITLE
上传较大文件报错，提示startChunk方法不存在

### ISSUE THREAD

**Issue by weeisc** [Slowlyo/owl-admin#36]
The route admin-api/api/upload/startChunk could not be found.

**Comment by Slowlyo** [comment]
如果文件过大，则可能需要使用分块上传，默认大于 5M（chunkSize 配置决定） 的文件是会自动开启，__可以通过 useChunk 配置成 false 关闭__。

[>>官方文档](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-file#%E5%88%86%E5%9D%97%E4%B8%8A%E4%BC%A0)

**Comment by weeisc** [comment]
看了官方的文档，把那三个接口实现了，100M左右的文件分块传下是比单传快
