### ISSUE TITLE
upload_file接口上传文件后返回的本地路径不对

### ISSUE THREAD

**Issue by weeisc** [Slowlyo/owl-admin#37]
vendor/slowlyo/owl-admin/src/Traits/UploadTrait.php文件，
![image](https://github.com/Slowlyo/owl-admin/assets/8087237/4e0f2441-b9bf-4388-9555-8434ae893c71)
图里直接返回`$path`不对吧，
是不是要这样处理下`Storage::path($path)`，我看富文本上传都加了这行
```php
$link = Storage::disk(Admin::config('admin.upload.disk'))->url($path);
```

**Comment by Slowlyo** [comment]
推荐保存不含域名的文件路径, 方便环境/域名更换~

可根据自身业务, 自行调整

框架默认解决方案👉[FAQ](https://github.com/Slowlyo/owl-admin/discussions/14)
