### ISSUE TITLE
nwidart module has been changed

### ISSUE THREAD

**Issue by ZhankaiWang** [Slowlyo/owl-admin#46]
The nwidart/laravel-modules module has modified the directory structure, and when executed

PHP Artisan module: make Test
PHP Artisan management module: init -- module=Test

An error will occur.

**Comment by Slowlyo** [comment]
请提供错误详细信息或者截图

**Comment by ZhankaiWang** [comment]
INFO  Module [Test] created successfully.  
 php artisan admin-module:init --module=Ticket

   ErrorException 

  file_put_contents(/Users/david/sites/amis/Modules/Test/Http/Controllers/AuthController.php): Failed to open stream: No such file or directory

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:205
    201▕      * @return int|bool
    202▕      */
    203▕     public function put($path, $contents, $lock = false)
    204▕     {
  ➜ 205▕         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    206▕     }
    207▕ 
    208▕     /**
    209▕      * Write the contents of a file, replacing it atomically if it already exists.

      +16 vendor frames 

  17  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))



nwidart/laravel-modules 生成的目录Http,Models,Providers这三个目录从模块的根目录移动到了app目录下，原来的init模块找不到路径

**Comment by Slowlyo** [comment]
`nwidart/laravel-modules:^10` 暂时没有适配, 等待后续更新

**Comment by Slowlyo** [comment]
在 `v3.0.3` 版本中已适配
