### ISSUE TITLE
最新版中在bootstrap中增加顶部菜不起作用，原版可以

### ISSUE THREAD

**Issue by ZhankaiWang** [Slowlyo/owl-admin#47]
最新版中在bootstrap中增加顶部菜不起作用

// file: App/Admin/bootstrap.php

<?php

// 一个按钮, 点击后弹出消息框
$msgBtn = amis()
    ->DrawerAction()
    ->icon('fa fa-bell')
    ->className('mr-2 rounded-full')
    ->drawer(
        amis()->Drawer()->title('Message')->body('Message Content')
    );

// 一个按钮, 点击后跳转到百度
$urlBtn = amis()
    ->UrlAction()
    ->icon('fa fa-magnifying-glass')
    ->className('ml-2 rounded-full')
    ->url('https://www.baidu.com')
    ->blank();

// 追加到已有按钮前
\Slowlyo\OwlAdmin\Admin::prependNav($msgBtn);

// 追加到已有按钮后
\Slowlyo\OwlAdmin\Admin::appendNav($urlBtn);

// 或者你可以这么写, 效果是一样的
// \Slowlyo\OwlAdmin\Admin::prependNav($msgBtn)->appendNav($urlBtn);

**Comment by Slowlyo** [comment]
![image](https://github.com/Slowlyo/owl-admin/assets/94038215/f5d0b8ca-b00c-4c72-bca4-207fd88d8146)

经测试, 无次问题

检查自己的代码是否正确
