### ISSUE TITLE
图片组件在表单中修改src不成功；

### ISSUE THREAD

**Issue by zydroot** [Slowlyo/owl-admin#48]
你好。
`public function form($isEdit = false): Form
    {

        return $this->baseForm()->body([
            amis()->TextControl('title', '名称'),
			amis()->ImageControl('thumbnail', '图片')
                ->src([env('APP_URL'). Storage::url('${thumbnail}')]),
			amis()->TextControl('order', '排序'),
			amis()->SwitchControl('statu', '启用'),
        ]);
    }`

这里使用了src修改图片默认显示url；
thumbnail数据库地址是：images/kxYbBLxSOxwn8O8v2lzYNj0BNaq4iANuzKo6M2tP.jpg
![xxx](https://github.com/Slowlyo/owl-admin/assets/4001375/e7cf0f2e-21c6-45b0-b6e0-30cfafd92b26)
结果如上图，src的地址还是数据库的，没有变化；

同样的修改方式，list  和 detail 都没有问题；
求帮助

**Comment by Slowlyo** [comment]
- https://bbs.csdn.net/topics/617244730
- https://bbs.csdn.net/topics/617293596

**Comment by zydroot** [comment]
感谢回复，没有忘记执行 php artisan storage:link
使用修改器也可以实现，不过表单保存需要处理数据。
以我做的程序为例，默认是相对路径保存；images/kxYbBLxSOxwn8O8v2lzYNj0BNaq4iANuzKo6M2tP.jpg

**Comment by Slowlyo** [comment]
> 感谢回复，没有忘记执行 php artisan storage:link 使用修改器也可以实现，不过表单保存需要处理数据。 以我做的程序为例，默认是相对路径保存；images/kxYbBLxSOxwn8O8v2lzYNj0BNaq4iANuzKo6M2tP.jpg

so? 还有什么问题?

**Comment by zydroot** [comment]
暂时就是这个了。谢谢回复。我在项目里再使用看看，感谢开发分享
