### ISSUE TITLE
编辑 / 详情页面数据回显失败? 提示 fetchFailed?

### ISSUE THREAD

**Issue by Slowlyo** [Slowlyo/owl-admin#5]
#### 原因:

字段名存在 status 或 no , 与 `amis` 关键字冲突
<a href="https://github.com/baidu/amis/issues/4055" target="_blank">
#4055: form 表单 initApi，服务端返回的 data 中包含 no、status 字段时，客户端处理异常
</a>

#### 解决方案:

1. 更改字段名
2. 使用 `属性修改器`
3. 等待 amis 修复

**Comment by SangBoy** [comment]
将前端主体框架的拦截器和amis的分开写就能解决这个问题

**Comment by slowlyo** [comment]
> 将前端主体框架的拦截器和amis的分开写就能解决这个问题

怕不是这个原因哦😅

**Comment by SangBoy** [comment]
> > 将前端主体框架的拦截器和amis的分开写就能解决这个问题
> 
> 怕不是这个原因哦😅



> > 将前端主体框架的拦截器和amis的分开写就能解决这个问题
> 
> 怕不是这个原因哦😅

当然不是简单的copy一份一样的，我通过这个方法就修复了这个问题...

**Comment by jcleng** [comment]
解决了吗, 这个问题直接一来就劝退了, 几乎所有的表都有status

**Comment by slowlyo** [comment]
> 解决了吗, 这个问题直接一来就劝退了, 几乎所有的表都有status

暂时没有
