### ISSUE TITLE
富文本报错，无法上传文件(图片)

### ISSUE THREAD

**Issue by taoyao-code** [Slowlyo/owl-admin#51]
<img width="838" alt="image" src="https://github.com/Slowlyo/owl-admin/assets/38855041/b4042389-88a0-4782-94ef-1394fb970a0a">

```json
{
        "type": "input-rich-text",
        "name": "rich",
        "label": "Rich Text"
}
```

**Comment by Slowlyo** [comment]
于 [v3.0.7](https://github.com/Slowlyo/owl-admin/releases/tag/v3.0.7) 已修复
