### ISSUE TITLE
 自定义新的富文本组件AiEditor

### ISSUE THREAD

**Issue by qq781548819** [Slowlyo/owl-admin#53]
### 是否关联于某个问题吗：
因为我没办法实现 自定义新的富文本组件
想接入 aieditor：https://gitee.com/aieditor-team/aieditor

### 预期的解决方案：
提供开箱即用的接入方案

### 任何附加信息：
![image](https://github.com/Slowlyo/owl-admin/assets/13780920/b36fcbd1-24fd-4f70-a69d-7730a5137d6e)

**Comment by Slowlyo** [comment]
后面研究一下🤔
