### ISSUE TITLE
文档v3.10 》入门》自定义业务逻辑》此处报错

### ISSUE THREAD

**Issue by piaohan** [Slowlyo/owl-admin#55]
![image](https://github.com/Slowlyo/owl-admin/assets/12056081/2c20947e-6268-49d7-8686-d192daca1368)
报错如下：
![image](https://github.com/Slowlyo/owl-admin/assets/12056081/cb5ece6f-899b-435b-aefd-1ff3fa46a1d4)

**Comment by Slowlyo** [comment]
amis()->TextControl()
