### ISSUE TITLE
BUG：菜单不能自动关闭，菜单会自动打开

### ISSUE THREAD

**Issue by ZhankaiWang** [Slowlyo/owl-admin#57]
### 描述问题：

点击菜单后，菜单不会自动关闭。

只要切换菜单，菜单会自动打开，而且不会关闭,其它布局也是一样

### 截图或视频：

![image](https://github.com/Slowlyo/owl-admin/assets/20102912/43fc4cdf-1131-4696-a848-c4d5760aadaf)
点击上面的《i服务》后，上部的菜单会自动打开，而且不会关闭
![image](https://github.com/Slowlyo/owl-admin/assets/20102912/be466be1-2555-4779-a1d4-582bb79cc24c)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

3.0.9-3.1.0

2. 运行环境

3. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by Slowlyo** [comment]
v3.1.1 已修复
