### ISSUE TITLE
请问这是什么情况？

### ISSUE THREAD

**Issue by piaohan** [Slowlyo/owl-admin#58]
### 描述问题：

登录后端页面后，js报错如下，使用 php artisan admin:update 更新后，使用 php artisan admin:publish --force --assets 和 php artisan admin:publish --force --views 还是这样

前几天还是好的，项目没有动过

### 截图或视频：

![image](https://github.com/Slowlyo/owl-admin/assets/12056081/72e9ee31-7725-4ee9-b3b6-3ef938824e35)

![image](https://github.com/Slowlyo/owl-admin/assets/12056081/9f7ee078-84be-4dbe-b8ca-f25552a8ae89)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

2. 运行环境

Win+laragon3+php8.0.12

3. 操作步骤
4. 
登录后端页面后，js报错如下

**Comment by Slowlyo** [comment]
把控制器里面页面的内容注释掉   强刷试试

**Comment by piaohan** [comment]
![image](https://github.com/Slowlyo/owl-admin/assets/12056081/12d46429-7b14-441c-b9fa-9e0aa9e868f3)
几个控制器都注释 单 好像 还是不行

**Comment by piaohan** [comment]
> 把控制器里面页面的内容注释掉 强刷试试
![image](https://github.com/Slowlyo/owl-admin/assets/12056081/7dab7ef6-b4d4-4720-8ad2-396fba277353)
几个都注释掉了，好像还是不行
![image](https://github.com/Slowlyo/owl-admin/assets/12056081/d5af7baf-c35d-4537-a612-b89c4cec35cf)
无痕mo'shi模式下 也不行

**Comment by Slowlyo** [comment]
3.1.0？

**Comment by Slowlyo** [comment]
换官方源   更新最新版本

**Comment by piaohan** [comment]
> 换官方源 更新最新版本

切换官方源后，进行更新，错误还是存在，我这边重新拉新的laravel 然后重新安装扩展，就不会出现这个问题。我今天有新的操作就是拉了     "name": "overtrue/laravel-wechat",
            "version": "7.2.0", 这个扩展。其他的没动过 不知道是不是这个原因

**Comment by Slowlyo** [comment]
不清楚   信息太少  定位不到问题

**Comment by piaohan** [comment]
我定位了下，应该不是，我切回原先的数据库 就会报这个错误

**Comment by piaohan** [comment]
我复现了

**Comment by Slowlyo** [comment]
哦哦    把admin_settings表里面的主题配置信息删了  然后清理下缓存就好了………   忘了这茬了😓

**Comment by piaohan** [comment]
哈哈

**Comment by piaohan** [comment]
可以 加个命令 去做清除缓存用

**Comment by piaohan** [comment]
1. admin_settings 删除了信息；
2. 命令运行了 php artisan cache:clear

我是还缺少哪步吗？应该还是不能用

**Comment by Slowlyo** [comment]
别用国内源的3.0.8应该就没问题了
