### ISSUE TITLE
无法使用 `laravel-debugbar` 调试

### ISSUE THREAD

**Issue by Heier2013** [Slowlyo/owl-admin#59]
### 描述问题：

安装完 [laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) 后，页面无法正常显示debug bar

### 截图或视频：

![截屏2023-12-26 22 04 17](https://github.com/Slowlyo/owl-admin/assets/9792980/ff64cf1b-8cf5-44c5-ab26-ae246ccdf575)
![截屏2023-12-26 22 06 23](https://github.com/Slowlyo/owl-admin/assets/9792980/84570cca-bd55-49d8-a69a-8e79f76e4d27)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

v3.1.0 其它版本也有问题

2. 运行环境

`Mac + Php Server`

3. 操作步骤

`composer require barryvdh/laravel-debugbar --dev`

**Comment by Slowlyo** [comment]
因为 owl admin 是前后端分离的项目, 目前暂不支持.

laravel-debugber 默认只支持类似 laravel-admin / dcat-admin 这类由后端渲染页面的框架. 

后续可能会在框架内适配, 或者通过扩展的形式支持~

**Comment by Heier2013** [comment]
感谢回复

类似的框架 [amis-admin](https://github.com/SmallRuralDog/amis-admin) 是支持的，希望能有帮助。
![image](https://github.com/Slowlyo/owl-admin/assets/9792980/5222557c-510d-45ff-b382-b9fc402d5c7c)

**Comment by Slowlyo** [comment]
v3.1.2 已支持

**Comment by Heier2013** [comment]
感谢，已测试正常！
