### ISSUE TITLE
Bug:Module中的Config,admin-asset没有修改

### ISSUE THREAD

**Issue by ZhankaiWang** [Slowlyo/owl-admin#60]
### 描述问题：

最新的3.1.2中src/Console/Module/stubs/initCommand.php和UpdateCommand.php中的

if (is_file(public_path('admin/index.html'))) {
仍然是原来的，应该是if (is_file(public_path('admin-asset/index.html'))) {

模块中生成的config/admin.php中仍然是admin，而不是admin-asset
'logo'           => '/admin/logo.png',
 'default_avatar' => '/admin/default-avatar.png',

### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

你是在哪个版本的 owl-admin 上遇到的问题？

2. 运行环境

eg: `Win + Docker` `Mac + Sail` `Linux + BT`

3. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by Slowlyo** [comment]
3.1.3中已修复
