### ISSUE TITLE
可以设置固定列吗?

### ISSUE THREAD

**Issue by okbeng2** [Slowlyo/owl-admin#67]
列太多可以让重要的几列固定，可以配置固定在左侧还是右侧

rowActions列也能设置固定

**Comment by Slowlyo** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/table#%E5%9B%BA%E5%AE%9A%E5%88%97

**Comment by okbeng2** [comment]
$this->rowActions(true)->fixed("right")
