### ISSUE TITLE
可视化编辑器 带格式化功能吗?

### ISSUE THREAD

**Issue by okbeng2** [Slowlyo/owl-admin#68]
获取PHP代码 生成的代码 希望能格式化
![格式化](https://github.com/Slowlyo/owl-admin/assets/18585975/1fa3de59-2a79-4175-8192-5c04b53be121)

vscode 用什么插件能格式化?

**Comment by Slowlyo** [comment]
https://blog.csdn.net/qq_23375733/article/details/105600574

**Comment by okbeng2** [comment]
> https://blog.csdn.net/qq_23375733/article/details/105600574
PHP Intelephense 只能格式化成这样... 不理想,还有其它方法吗?
![格式化](https://github.com/Slowlyo/owl-admin/assets/18585975/08bcd837-d9db-4d48-a560-423a9d96c8ef)

**Comment by Slowlyo** [comment]
换 phpstorm
