### ISSUE TITLE
请多出一些多表关联的配置使用教程

### ISSUE THREAD

**Issue by TimeIsGoOn** [Slowlyo/owl-admin#71]
我有三个表，老师， 班级 ，和学生表。学生有一个所属班级字段。

班级表有一个字段是管理老师，其实也对应的当前登录系统的用户。

我希望在编辑学生的时候，所属班级那里，显示为一个下拉。
同时，下拉列表里面，只展示当前用户管理的班级列表。

这种关联的操作，我不知道具体该如何配置，希望能在b站上多出一些教学视频

感谢

**Comment by Slowlyo** [comment]
关联查询, 主要是 `laravel` 的使用问题, `owl-admin` 只是取值并展示

参考: 
- [数据域](https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/datascope-and-datachain)
- [模型关联数据展示](http://doc.owladmin.com/#/examples/model-relation)

**Comment by chenjiabin** [comment]
您好， 一对多， save 是不是要自己写service呀
