### ISSUE TITLE
问题：nwidart/laravel-modules 更新后，模块初始化错误

### ISSUE THREAD

**Issue by emonduora** [Slowlyo/owl-admin#73]
### 描述问题：

nwidart/laravel-modules 模块更新，导致模块初始化错误，默认Models目录不存在，并且 app目录已经更改为App

生成的空间， namespace Modules\Apim\app\Models; 还是小写

### 截图或视频：
执行 php artisan admin-module:init --module=Apim

<img width="940" alt="image" src="https://github.com/Slowlyo/owl-admin/assets/156265314/80d64727-2918-48bb-8c6c-2233afaa71c6">

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

3.2.4

**Comment by Slowlyo** [comment]
他又改目录结构了....

前面已经适配过一次了😅

先回退版本使用吧, 后续可能考虑自己实现多模块功能

**Comment by Slowlyo** [comment]
`v3.2.6` 中, `modules` 功能已经不再依赖 `nwidart/laravel-modules`

已使用的模块, 需要手动迁移
