### ISSUE TITLE
版本升级消息提示框未正常显示

### ISSUE THREAD

**Issue by lostinyouu** [slowlyo/owl-admin#76]
### 描述问题：

版本v3.2.6升级v3.2.9以后

按照升级步骤执行 `php artisan admin:publish --assets --force`

消息提示框不显示，降级回v3.2.6正常显示

v.3.2.9 主题设置中保存配置按钮，正常显示，其他无显示。

![image](https://github.com/slowlyo/owl-admin/assets/20572151/a977d802-377c-4d0c-8cba-1a362e43f567)

**Comment by slowlyo** [comment]
v3.3.0 已修复
