### ISSUE TITLE
问题：升级到3.2.9，AdminMenu并没有更新

### ISSUE THREAD

**Issue by emonduora** [slowlyo/owl-admin#77]
### 描述问题：

升级到3.2.9，扩展多语言中AdminMenu并没有更新

### 截图或视频：

<img width="454" alt="image" src="https://github.com/slowlyo/owl-admin/assets/156265314/e8229562-7d6b-421b-a7d1-cece805afaaf">

https://github.com/slowlyo/owl-admin中的AdminMenu
<img width="842" alt="image" src="https://github.com/slowlyo/owl-admin/assets/156265314/dfe3daa0-bd22-4528-939c-cb8f5f1509e8">

升级到3.2.9后，本地的AdminMenu，并没有更新

![image](https://github.com/slowlyo/owl-admin/assets/156265314/8e08cc48-183f-4ae7-8388-cd5064f7b328)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

你是在哪个版本的 owl-admin 上遇到的问题？

2. PHP & Laravel 版本是什么？

php8.3 & laravel: 10.*.*

3. 运行环境

eg: `Win + Docker` `Mac + Sail` `Linux + BT`

4. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by slowlyo** [comment]
没发版呢    估计会在今天发😅
