### ISSUE TITLE
前端重新用react写的考量是什么？以前的vue中嵌套amis有限制还是？

### ISSUE THREAD

**Issue by xianlinzhang** [Slowlyo/owl-admin#8]
你好，有个问题请教下，前端重新用react写的考量是什么？以前的vue中嵌套amis有限制还是？

**Comment by Slowlyo** [comment]
> 你好，有个问题请教下，前端重新用react写的考量是什么？以前的vue中嵌套amis有限制还是？

更方便添加自定义组件

**Comment by xianlinzhang** [comment]
> > 你好，有个问题请教下，前端重新用react写的考量是什么？以前的vue中嵌套amis有限制还是？
> 
> 更方便添加自定义组件

好的，谢谢
