### ISSUE TITLE
问题：src/Renderers/DateRangControl中没有定义clearable属性，导致时间范围选择器无法清除

### ISSUE THREAD

**Issue by emonduora** [slowlyo/owl-admin#80]
### 描述问题：

amis()->DateRangeControl('dateRange','日期范围')
                            ->clearable(),

此render中不定义该函数则不会出现如图所示

### 截图或视频：

<img width="502" alt="image" src="https://github.com/slowlyo/owl-admin/assets/156265314/662b75ec-88af-4d29-928a-9035eab00812">

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

你是在哪个版本的 owl-admin 上遇到的问题？

2. PHP & Laravel 版本是什么？

php8.3 & laravel: 10.*.*

3. 运行环境

eg: `Win + Docker` `Mac + Sail` `Linux + BT`

4. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by slowlyo** [comment]
```php
amis()->DateRangeControl('dateRange','日期范围')->clearable(true)
```

这样不就好了

![image](https://github.com/slowlyo/owl-admin/assets/94038215/e13e43cf-3b8a-411c-abe3-09e075a919ab)

**Comment by emonduora** [comment]
谢谢，加true就可以了
