### ISSUE TITLE
Class "Laravel\Sanctum\Sanctum" not found

### ISSUE THREAD

**Issue by ahu** [slowlyo/owl-admin#83]
### 描述问题：

在 Laravel v11.0.3 安装好后，再安装 owl-admin 时，直接报错：Class "Laravel\Sanctum\Sanctum" not found

### 截图或视频：

![WX20240315-150632@2x](https://github.com/slowlyo/owl-admin/assets/330336/569c5f1c-5598-42d1-b262-239a4a1a4745)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

v3.3.9

2. PHP & Laravel 版本是什么？

php8.3.3 & laravel: 11.0.3

3. 运行环境

`Mac + Valet` 

4. 操作步骤

如上所示

**Comment by ahu** [comment]
解决办法： `composer require laravel/sanctum`

**Comment by slowlyo** [comment]
readme 在发版的时候就已经更新过了哦

![image](https://github.com/slowlyo/owl-admin/assets/94038215/cd3a15fc-b020-47ef-8edb-dd734fff688e)
