### ISSUE TITLE
开发扩展使用View模板的问题

### ISSUE THREAD

**Issue by emonduora** [slowlyo/owl-admin#85]
### 描述问题：

开发一个扩展，要用到视图模板
<img width="620" alt="image" src="https://github.com/slowlyo/owl-admin/assets/156265314/310e4e67-c9a5-46dd-a20c-2d990fd90c89">

但找不到： ERROR: View [mails.submit] not found.  ,必须放在laravel 的resources/views 那个目录下吗？

这个怎么解决？

### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

你是在哪个版本的 owl-admin 上遇到的问题？

2. PHP & Laravel 版本是什么？

php8.3 & laravel: 10.*.*

3. 运行环境

eg: `Win + Docker` `Mac + Sail` `Linux + BT`

4. 操作步骤

请简单描述一下复现的操作步骤...

**Comment by slowlyo** [comment]
或许可以试试

```php
view()->file('xxx')->name();
```

或者在服务提供者中注册视图
![image](https://github.com/slowlyo/owl-admin/assets/94038215/ec43a4c9-d853-442b-9aab-1099a8b0aa5c)
