### ISSUE TITLE
列表分页选项显示不全

### ISSUE THREAD

**Issue by leoxml** [slowlyo/owl-admin#96]
### 描述问题：

列表分页选项显示不全

### 截图：

当选择20条每页以上时，显示不完全

![96b8bb968012d4ef135df4bbee913cff](https://github.com/slowlyo/owl-admin/assets/6308377/6672215a-5ab3-4a59-b088-227e893e6a6d)

当选择10条每页时，显示正常

![6d29ef2175422bdece5d5220cbd7dfde](https://github.com/slowlyo/owl-admin/assets/6308377/1133454b-6148-4804-98ac-06d82a7d37f9)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

3.5.8

2. PHP & Laravel 版本是什么？

php8.3 & laravel: 11.3.1

3. 运行环境

Mac + nginx

**Comment by emonduora** [comment]
确实，大于10条时都是向下显示，显示不完整

**Comment by slowlyo** [comment]
已处理, 下版本修复

**Comment by slowlyo** [comment]
3.6.0 已修复

**Comment by leoxml** [comment]
> 3.6.0 已修复

![image](https://github.com/slowlyo/owl-admin/assets/6308377/0833718a-e27f-46c6-9863-25076c301230)

class是不是放在baseCRUD这里更合适些呢？

**Comment by leoxml** [comment]
![image](https://github.com/slowlyo/owl-admin/assets/6308377/2487da5d-248d-472e-8d19-9a44ab96b457)
 如果body里是tabs，每个tab一个列表，分页下拉选项依然是遮挡的
把这个class放每个tab()层就可以了
