### ISSUE TITLE
编辑文章的时候  裁剪图片提示跨域问题

### ISSUE THREAD

**Issue by ajiader** [slowlyo/owl-admin#97]
### 描述问题：

添加的时候裁剪没有问题；
编辑内容的时候  裁剪封面图提示跨域问题，后端配置了跨域结果还是报错

### 截图或视频：|
这个是后端配置跨域
![image](https://github.com/slowlyo/owl-admin/assets/4979798/0cf9bcc9-1dae-4286-9ba3-9877983ef448)
点击裁剪按钮
![image](https://github.com/slowlyo/owl-admin/assets/4979798/d5ee2aa7-656c-424e-a078-4145bdabef5d)
就提示跨域报错了
![image](https://github.com/slowlyo/owl-admin/assets/4979798/35294aa4-24f4-4637-a059-4b116a4ca83b)

**Comment by slowlyo** [comment]
估计是oss的原因, 实在不行就把需要裁剪的图片放本地吧
