### ISSUE TITLE
使用代码生成器 打开生成的页面 报错 

### ISSUE THREAD

**Issue by huagelong** [slowlyo/owl-admin#98]
### 描述问题：

使用代码生成器 打开生成的页面 报错 

```
The route admin-api/cms_index could not be found.
```

### 截图或视频：

![image](https://github.com/slowlyo/owl-admin/assets/531568/e79bed8d-6fc0-4c37-acc3-3d10e04ad77f)

### 如何复现（请务必完整填写下面内容）：

1. owl-admin 版本是什么？

    "name": "slowlyo/owl-admin",
    "version": "v3.5.8",

2. PHP & Laravel 版本是什么？

php8.1 & laravel: 10.10

3. 运行环境

windows

4. 操作步骤

按照代码生成器生成，打开菜单栏链接后报错

**Comment by slowlyo** [comment]
![image](https://github.com/slowlyo/owl-admin/assets/94038215/16c4a07f-01a0-4a81-ad6e-757128e74818)

检查这里的开关是否打开, 打开后执行 `php artisan admin:gen-route` 命令后再试试

**Comment by huagelong** [comment]
谢谢，刚刚我把vendor文件删除，重新 composer install 就好了
