### ISSUE TITLE
如何实现一个页面无顶部导航和左侧导航，纯页面

### ISSUE THREAD

**Issue by yangweijie** [slowlyo/owl-admin#99]
### 是否关联于某个问题吗：
可视化代码编辑器生成的页面 在admin 应用里 控制器方法里 执行，生成的是后台布局，有时候需要新开一些独立的页面也用amis去显示，且表格之类的无需鉴权，能否提供一个frontController 来实现它。

### 预期的解决方案：
在其他应用控制器继承frontController 可以使用amis api来构造页面

### 其他可接受方案：
请简单描述其他你可以接受的效果...

### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by slowlyo** [comment]
菜单管理里面有配置项
